[manager]
address = "100.87.99.20:50051"
retry_interval_s = 5

[service]
name = "pulseblaster-service"
description = "Call this service to program the SpinCore PulseBlaster "
address = "100.114.164.102:5055"
